# Prefix
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Theme
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode (Dark background, Everforest Green foreground)
setw -g clock-mode-colour "#A7C080"
setw -g clock-mode-style 24

# copy mode (Dark text on an Amber background)
setw -g mode-style 'fg=#2D353B bg=#E69875 bold'

# panes (Muted gray-green for borders, Aqua for active pane)
set -g pane-border-style 'fg=#4F585E'
set -g pane-active-border-style 'fg=#7FBBB3'

# statusbar (Foreground text on Status line background)
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=#D3C6AA bg=#232A2E'
set -g status-left ''
set -g status-left-length 10

# clock (Orange/Amber text on Status line background)
set -g status-right-style 'fg=#E69875 bg=#232A2E'
set -g status-right ' %Y-%m-%d %H:%M '
set -g status-right-length 50

# window status (Active tab gets dark text on clean Green bg)
setw -g window-status-current-style 'fg=#2D353B bg=#A7C080 bold'
setw -g window-status-current-format ' #I #W #F '

# inactive windows (Soft muted gray-green text)
setw -g window-status-style 'fg=#859289 bg=#232A2E'
setw -g window-status-format ' #I #[fg=#D3C6AA]#W #[fg=#7FBBB3]#F '

# bell alert state (Dark text on Red highlight)
setw -g window-status-bell-style 'fg=#2D353B bg=#E67E80 bold'

# messages / command prompt status (Warm Yellow text)
set -g message-style 'fg=#DBBC7F bg=#232A2E bold'
