set nocompatible
syntax on
set number
set relativenumber
set ruler
set encoding=utf-8
set wrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set noshiftround
set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch
set clipboard=unnamedplus
