import = ["/home/victor/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font"
style = "Semibold"

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
opacity = 0.85

[window.dimensions]
columns = 140
lines = 45

[window.padding]
x = 10
y = 10
