# [metadata]
# name = "carbonfox"
# author = "wjohnsto"
# origin_url = "https://github.com/EdenEast/nightfox.nvim"

"$schema" = "https://starship.rs/config-schema.json"

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
\n$character"""

[os]
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = " 󰣭 "
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
format = "[ $user ]($style)"

[directory]
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"src" = " "

[git_branch]
symbol = " "

[nodejs]
symbol = " "

[c]
symbol = " "

[rust]
symbol = " "

[golang]
symbol = " "

[python]
symbol = " "

[character]
disabled = false
success_symbol = '[](bold fg:#25be6a)'
error_symbol = '[](bold fg:#ee5396)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
