[General]
# Path to the background image
background=/usr/share/sddm/themes/everforest/everforest_lockscreen.png
# Blur radius for the background
blurRadius=0

# Color Scheme (Rose Pine Default / Fallback)
mPrimary=#A7C080
mOnPrimary=#2D353B
mSecondary=#7FBBB3
mOnSecondary=#2D353B
mTertiary=#DBBC7F
mOnTertiary=#2D353B
mError=#E67E80
mOnError=#2D353B
mSurface=#2D353B
mOnSurface=#D3C6AA
mSurfaceVariant=#343F44
mOnSurfaceVariant=#9DA9A0
mOutline=#4F585E
mShadow=#232A2E
mHover=#83C092
mOnHover=#2D353B
